develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35831:35729"
  container_name: rw-adapter-document-develop
  environment:
    NODE_ENV: dev
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4000
    API_VERSION: v1
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    STAMPERY_TOKEN:
    S3_ACCESS_KEY_ID:
    S3_SECRET_ACCESS_KEY:
    CT_REGISTER_MODE: auto
    RABBITMQ_URL: "amqp://user:password@mymachine:5672"
    ELASTIC_PORT_9200_TCP_ADDR: mymachine
    ELASTIC_PORT_9200_TCP_PORT: 9200
  command: develop
  volumes:
    - ./app:/opt/rw-adapter-document/app
