test:
  extends:
    file: base.yml
    service: base
  ports:
    - "4000"
  container_name: rw-adapter-document-test
  environment:
    NODE_ENV: test
  command: test
  links:
    - mongo

mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017"

elastic:
  image: vizzuality/elasticsearch-sql:1.0.0
  ports:
    - "9200"
    - "9300"
