prod:
  image: vizzuality/rw-adapter-document:1.2.7${STAGING}
  ports:
    - "4000"
  env_file:
    - prod.env
  links:
    - redis
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  container_name: rw-adapter-document-api
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw-adapter-document-api${STAGING}
