develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35731:35729"
  container_name: rw-adapter-csv-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://192.168.99.100:8000
  command: develop
  links:
    - redis
    - elastic
  volumes:
    - ./app:/opt/rw-adapter-csv/app
worker:
  build: .
  environment:
    NODE_PATH: app/src
    NODE_ENV: dev
  container_name: rw-adapter-csv-worker-develop
  command: developWorker
  links:
    - redis
    - elastic
  volumes_from:
    - develop
redis:
  image: redis
  container_name: rw-adapter-csv-redis
  ports:
    - "6379"
  restart: always
elastic:
  image: vizzuality/elasticsearch-sql:1.0.0
  container_name: rw-adapter-csv-elastic
  ports:
    - "9200"
    - "9300"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/rw-adapter-csv-elastic:/usr/share/elasticsearch/data
  restart: always
