prod:
  image: vizzuality/rw-adapter-csv:1.2.0${STAGING}
  ports:
    - "4000"
  env_file:
    - prod.env
  links:
    - redis
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw-adapter-csv${STAGING}
worker:
  image: vizzuality/rw-adapter-csv:1.2.0${STAGING}
  env_file:
    - prod.env
  links:
    - redis
  command: startWorker
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw-adapter-csv${STAGING}
redis:
  image: redis
  ports:
    - "6379"
  restart: always
