prod:
  image: vizzuality/rw-adapter-csv:1.1.3${STAGING}
  ports:
    - "4000"
  env_file:
    - prod.env
  links:
    - redis
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: rw-adapter-csv${STAGING}
worker:
  image: vizzuality/rw-adapter-csv:1.1.2${STAGING}
  env_file:
    - prod.env
  links:
    - redis
  command: startWorker
  dns: ${DNS_SERVER}
  restart: always
  # log_driver: "gelf"
  # log_opt:
  #   gelf-address: ${GELF_ADDRESS}
redis:
  image: redis
  ports:
    - "6379"
  restart: always
